mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from polls import views as main_views
from rest_framework.urlpatterns import format_suffix_patterns

urlpatterns = [
    path('', main_views.home),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('poll', main_views.questionList.as_view()),

]

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    # ex: http://127.0.0.1:8000
    path('', views.home, name='home'),
    # ex: /polls/
    path('index/', views.index, name='index'),
    # ex: /polls/5/
    path('<int:question_id>/', views.detail, name='detail'),
    # ex: /polls/5/results/
    path('<int:question_id>/results/', views.results, name='results'),
    # ex: /polls/final/
    path('final/', views.finalvotes, name='final'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),

    path('raffle/', views.user_email, name='raffle'),

    path('thankyou/', views.thankyou, name='thankyou'),
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

        
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    choice_image = models.CharField(max_length=200, default='')
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

class User(models.Model):
    First_Name = models.CharField(max_length=50, default='')
    Email = models.CharField(max_length=100, default='')
    def __str__(self):
        return self.Email

polls/forms.py
from django import forms
from polls.models import User
from django.forms import ModelForm

#class NameForm(forms.Form):
    #form = forms.CharField(label='Your email', max_length=100)

class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['First_Name', 'Email']
# TO ALTER FORM ON WEBSITE, JUST ALTER MODEL AND FORM FIELDS
# MAKE SURE FIELD IN FORM CLASS CLASS MATCHES FIELD IN MODEL CLASS

polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from .models import Question
# from .forms import NameForm
from .forms import UserForm

from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from . serializers import questionSerializer




def home(request):
    return render(request, 'polls/home.html')

def index(request):
    #latest_question_list = Question.objects.order_by('-pub_date')[:5]
    question_list = Question.objects.all()
    context = {'latest_question_list': question_list}
    return render(request, 'polls/index.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })

def finalvotes(request):
    question_list = Question.objects.all()
    return render(request, 'polls/finalvotes.html', {
            'question_list': question_list,
            'error_message': "",
        })

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

'''def get_email(request):

   if request.method == 'POST':
       # create a form instance and populate it with data from the request:
       form = NameForm(request.POST)
       # check whether it's valid:
       if form.is_valid():
            form = form.save(commit=False)

           # process the data in form.cleaned_data as required
           # ...
           # redirect to a new URL:
            return HttpResponseRedirect(reverse('polls:thankyou'))

       # if a GET (or any other method) we'll create a blank form
   else:
       form = NameForm()

   return render(request, 'polls/raffle.html', {'form': form})
'''


def user_email(request):
    if request.method == "POST":
        form = UserForm(request.POST)

        if form.is_valid():
            model_instance =form.save(commit=False)
            model_instance.save()
            return HttpResponseRedirect(reverse('polls:thankyou'))
    else:
        form = UserForm()

    return render(request, 'polls/raffle.html', {'form': form})



def thankyou(request):
    # question_list = Question.objects.all(),
    return render(request, 'polls/thankyou.html')



class questionList(APIView):
    def get(self, request):
        questions1 = Question.objects.all()
        serializer=questionSerializer(questions1, many=True)
        return Response(serializer.data)

    def post(self):
        pass

polls/templates/polls/detail - Copy.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

polls/templates/polls/detail.html
{% load static %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Survey|Golden Arch LLC. ">
    <meta name="keywords" content="Survey,Golden Arch">
    <link rel="shortcut icon" href="{% static "polls/i/favicon.ico" %}" />
    <link rel="icon" href="{% static "polls/i/favicon.ico" %}" />
    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->

    <title>Skin Care Survey|Golden Arch LLC.</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/polls/css/bootstrap.min.css" rel="stylesheet" />

  	<!-- fancyBox -->
	<link rel="stylesheet" href="/static/polls/css/fancybox/jquery.fancybox.css" type="text/css" media="screen" />

    <link href="{% static 'polls/css/main.css' %}" rel="stylesheet" />
    <!--<link href="/static/polls/css/main.css" rel="stylesheet" /> -->

     <script src="/static/polls/js/jquery/jquery-1.12.0.min.js"></script>

</head>
<body>
<div class="container">
    <div class="visible-sm-block visible-md-block visible-lg-block">
        <img u="image" src="{% static "polls/i/header.jpg" %}" class="img-responsive"/>
    </div>
             
     <div class="visible-xs-block">
        <div><img u="image" src="/static/polls/i/header.jpg" class="img-responsive"/></div>
    </div>
</div>
<div class="container" >
    <div class="main-content">
            <form action="{% url 'polls:vote' question.id %}" method="post">
                {% csrf_token %}
                <div class="row featurette">
                    <div class="col-xs-12 col-sm-12 col-md-1"></div>
                    <div class="col-xs-12 col-sm-12 col-md-10">
                        <div style="float:inherit">
                            <h1>{{ question.question_text }}</h1><br/><br/>
                        </div>
                    </div>
                </div>
                <div class="row featurette">
                    <div class="col-xs-12 col-sm-12 col-md-10">
                        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
                    </div>
                </div>
                <div class="row featurette">
                    {% for choice in question.choice_set.all %}
                    <div class="col-xs-12 col-sm-6 col-md-3">
                        <div class="panel panel-default">
                            <div class="panel-body"><img src="/static/polls/i/product/{{ choice.choice_image }}" class="img-responsive float-img" alt=""></div>
                            <div class="panel-footer">
                                <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" >
                                <span class="event-title" for="choice{{ forloop.counter }}">{{ choice.choice_text }}</span>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div><br/><br/><br/><br/>
                <div class="row featurette">
                        <div class="col-xs-12 col-sm-2 col-md-8">
                        </div>
                        <div class="col-xs-12 col-sm-9 col-md-4">
                            <input type="image" src="/static/polls/i/btn_submit.png" value="Submit">
                        </div>
                </div>
            </form><br/><br/><br/><br/><br/><br/><br/><br/>
        <hr />  <!-- featurette-divider -->
        <!-- FOOTER -->
        <footer>
            <div class="copyRight">&copy; Copyright 2019 CN CONNECTION GOLDEN ARCH LLC. All Rights Reserved.</div>
        </footer>
        <br /><br />
    </div>

</div>
<!-- end of .container -->

<!-- Placed at the end of the document so the pages load faster -->
<script src="{% static "polls/js/plugin/bootstrap-3.3.6.min.js" %}"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script type="text/javascript" src="{% static "polls/js/plugin/ie10-viewport-bug-workaround.js" %}"></script>

<!-- fancybox -->
<script type="text/javascript" src="{% static "polls/js/plugin/jquery.fancybox.pack.js" %}"></script>

</body>
</html>

polls/templates/polls/finalvotes.html
{% load static %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Survey|Golden Arch LLC. ">
    <meta name="keywords" content="Survey,Golden Arch">
    <link rel="shortcut icon" href="{% static "polls/i/favicon.ico" %}" />
    <link rel="icon" href="{% static "polls/i/favicon.ico" %}" />
    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->

    <title>Skin Care Survey|Golden Arch LLC.</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/polls/css/bootstrap.min.css" rel="stylesheet" />

  	<!-- fancyBox -->
	<link rel="stylesheet" href="/static/polls/css/fancybox/jquery.fancybox.css" type="text/css" media="screen" />

    <link href="{% static 'polls/css/main.css' %}" rel="stylesheet" />
    <!--<link href="/static/polls/css/main.css" rel="stylesheet" /> -->

     <script src="/static/polls/js/jquery/jquery-1.12.0.min.js"></script>

</head>
<body>
<div class="container">
    <div class="visible-sm-block visible-md-block visible-lg-block">
        <img u="image" src="{% static "polls/i/header.jpg" %}" class="img-responsive"/>
    </div>
                         
    <div class="visible-xs-block">
        <div><img u="image" src="/static/polls/i/header.jpg" class="img-responsive"/></div>
    </div>
</div>

<div class="container" >
    <div class="main-content">
        {% csrf_token %}
        {% if question_list %}
            {% for question in question_list %}
                <div class="row featurette">
                    <div class="col-xs-12 col-sm-12 col-md-1"></div>
                    <div class="col-xs-12 col-sm-12 col-md-10">
                        <div style="float:inherit">
                            <h2><a href="{% url 'polls:detail' question.id %}">{{ question.id }}. {{ question.question_text }}</a></h1>
                        </div>
                    </div>
                </div>
                 <div class="row featurette">
                    <ul>
                    {% for choice in question.choice_set.all %}
                        <div class="col-xs-12 col-sm-12 col-md-10">
                            <li style="color: #1b3fa9; font-size:18px; font-weight:400; line-height:35px; margin-left: 100px;	">
                                {{ choice.choice_text }} -- <span style="color:rgb(173, 4, 41)">{{ choice.votes }} vote{{ choice.votes|pluralize }}</span>
                            </li>
                        </div>
                    {% endfor %}
                     </ul>
                </div>
            {% endfor %}
            <br/><br/><br/><br/>
            <div class="row featurette">
                <div class="col-xs-12 col-sm-12 col-md-12" style="padding-left: 200px; vertical-align: top;">

                    <a href="{% url 'polls:final' %}"><img src="{% static "polls/i/btn_done.png" %}"/></a>
                </div>
            </div>
         {% else %}
            <p>No polls are available.</p>
         {% endif %}
        <br/><br/><br/><br/><br/><br/><br/><br/>
        <hr />  <!-- featurette-divider -->
        <!-- FOOTER -->
        <footer>
            <div class="copyRight">&copy; Copyright 2019 CN CONNECTION GOLDEN ARCH LLC. All Rights Reserved.</div>
        </footer>
        <br /><br />
    </div>

</div>
<!-- end of .container -->

<!-- Placed at the end of the document so the pages load faster -->
<script src="{% static "polls/js/plugin/bootstrap-3.3.6.min.js" %}"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script type="text/javascript" src="{% static "polls/js/plugin/ie10-viewport-bug-workaround.js" %}"></script>

<!-- fancybox -->
<script type="text/javascript" src="{% static "polls/js/plugin/jquery.fancybox.pack.js" %}"></script>

</body>
</html>

polls/templates/polls/home.html
{% load static %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Survey|Golden Arch LLC. ">
    <meta name="keywords" content="Survey,Golden Arch">
    <link rel="shortcut icon" href="{% static "polls/i/favicon.ico" %}" />
    <link rel="icon" href="{% static "polls/i/favicon.ico" %}" />
    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->

    <title>Skin Care Survey|Golden Arch LLC.</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/polls/css/bootstrap.min.css" rel="stylesheet" />

  	<!-- fancyBox -->
	<link rel="stylesheet" href="/static/polls/css/fancybox/jquery.fancybox.css" type="text/css" media="screen" />

    <link href="/static/polls/css/main.css" rel="stylesheet" />

    <script src="/static/polls/js/jquery/jquery-1.12.0.min.js"></script>

</head>
<body>
<div class="container">
    <!-- Jssor Slider Begin -->
    <div id="slider1_container" class="slideContainer visible-sm-block visible-md-block visible-lg-block">

        <!-- Loading Screen -->
        <div u="loading" style="position: absolute; top: 0px; left: 0px;">
            <div class="loading1"></div>
            <div class="loading2"></div>
        </div>

        <!-- Slides Container -->
        <div u="slides" class="slides">
                <div><img u="image" src="{% static "polls/i/slide-1.jpg" %}" /></div>
                <div><img u="image" src="{% static "polls/i/slide-2.jpg" %}" /></div>
                <div><img u="image" src="{% static "polls/i/slide-3.jpg" %}" /></div>
                <div><img u="image" src="{% static "polls/i/slide-4.jpg" %}" /></div>
                <div><img u="image" src="{% static "polls/i/slide-5.jpg" %}" /></div>
                <div><img u="image" src="{% static "polls/i/slide-6.jpg" %}" /></div>    
        </div>              

        <!-- bullet navigator container -->
        <div u="navigator" class="jssorb05">
            <div u="prototype"></div> 
        </div>
           
        <!-- Arrow Left -->
        <span u="arrowleft" class="jssora11l"></span>
        <!-- Arrow Right -->
        <span u="arrowright" class="jssora11r"></span>
            
    </div>
    <!-- Jssor Slider End -->

    <!-- Static small image for mobile -->
    <div class="visible-xs-block">
        <div><img u="image" src="/static/polls/i/slide-1s.jpg" class="img-responsive"/></div>
    </div>

</div>

<div class="container" >
    <div class="main-content">
        <div class="row featurette">
        <div class="hidden-xs hidden-sm col-md-2">
        </div>
        
        <div class="col-xs-12 col-sm-12 col-md-8">
            <h2>Product Survey</h2><br/>
            <h3>please take our survey to help us improve our products and services so that we can better serve you</h3>
                
            <h1><a href="{% url 'polls:index' %}"><img src="{% static "polls/i/btn_start.png" %}"/></a></h1>
        </div>
        </div>
        <br/><br/><br/><br/>
        <hr />  <!-- featurette-divider -->

        <!-- FOOTER -->
        <footer>
            <div class="copyRight">&copy; Copyright 2019 CN CONNECTION GOLDEN ARCH LLC. All Rights Reserved.</div>
        </footer>
    </div>

</div>
<!-- end of .container -->

<!-- Placed at the end of the document so the pages load faster -->
<script src="{% static "polls/js/plugin/bootstrap-3.3.6.min.js" %}"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script type="text/javascript" src="{% static "polls/js/plugin/ie10-viewport-bug-workaround.js" %}"></script>

<!-- jssor slider scripts-->
<script type="text/javascript" src="{% static "polls/js/plugin/jssor.slider.mini.js" %}"></script>

<!-- initialize slider -->
<script type="text/javascript" src="{% static "polls/js/slider.js" %}"></script>

<!-- fancybox -->
<script type="text/javascript" src="{% static "polls/js/plugin/jquery.fancybox.pack.js" %}"></script>

</body>
</html>

polls/templates/polls/index - Copy.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
    <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/index.html
{% load static %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Survey|Golden Arch LLC. ">
    <meta name="keywords" content="Survey,Golden Arch">
    <link rel="shortcut icon" href="{% static "polls/i/favicon.ico" %}" />
    <link rel="icon" href="{% static "polls/i/favicon.ico" %}" />
    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->

    <title>Skin Care Survey|Golden Arch LLC.</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/polls/css/bootstrap.min.css" rel="stylesheet" />

  	<!-- fancyBox -->
	<link rel="stylesheet" href="/static/polls/css/fancybox/jquery.fancybox.css" type="text/css" media="screen" />

    <link href="{% static 'polls/css/main.css' %}" rel="stylesheet" />
    <link href="/static/polls/css/main.css" rel="stylesheet" /> 

    <script src="/static/polls/js/jquery/jquery-1.12.0.min.js"></script>

</head>
<body>
<div class="container">
    <div class="visible-sm-block visible-md-block visible-lg-block">
        <img u="image" src="{% static "polls/i/header.jpg" %}" class="img-responsive"/>
    </div>
 
    <div class="visible-xs-block">
        <div><img u="image" src="/static/polls/i/header.jpg" class="img-responsive"/></div>
    </div>
</div>

<div class="container" >
    <div class="main-content">
    <div class="row featurette">
        <div class="hidden-xs hidden-sm col-md-2">

        </div>

        <div class="col-xs-12 col-sm-12 col-md-8">
            <h2>Product Survey</h2><br/>
            <h3> please take our survey to help us improve our products and services so that we can better serve you</h3><br/><br/>
            {% if latest_question_list %}
                <h4><ul>
                {% for question in latest_question_list %}
                <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li><br/><br/>
                {% endfor %}
                </ul></h4>
            {% else %}
                <p>No polls are available.</p>
            {% endif %}
        </div>
    </div>
        <hr />  <!-- featurette-divider -->
        <!-- FOOTER -->
        <footer>
            <div class="copyRight">&copy; Copyright 2019 CN CONNECTION GOLDEN ARCH LLC. All Rights Reserved.</div>
        </footer>
        <br /><br />
    </div>

</div>
<!-- end of .container -->

<!-- Placed at the end of the document so the pages load faster -->
<script src="{% static "polls/js/plugin/bootstrap-3.3.6.min.js" %}"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script type="text/javascript" src="{% static "polls/js/plugin/ie10-viewport-bug-workaround.js" %}"></script>

<!-- fancybox -->
<script type="text/javascript" src="{% static "polls/js/plugin/jquery.fancybox.pack.js" %}"></script>

</body>
</html>

polls/templates/polls/raffle.html
<h3> Please enter your email for a chance to win a $100 gift card</h3>


<form action="{% url 'polls:raffle' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <p><input type="checkbox"> Subscribe to our monthly newsletter<br></p>

<input type="submit" value="Enter raffle">
</form>

polls/templates/polls/results - Copy.html
<h1>{{ q.question_text }}</h1>

<ul>
{% for choice in q.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>
<div>
{{error_message}}
</div>

<a href="{% url 'polls:detail' q.id %}">Vote again?</a>

polls/templates/polls/results.html
{% load static %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Survey|Golden Arch LLC. ">
    <meta name="keywords" content="Survey,Golden Arch">
    <link rel="shortcut icon" href="{% static "polls/i/favicon.ico" %}" />
    <link rel="icon" href="{% static "polls/i/favicon.ico" %}" />
    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->

    <title>Skin Care Survey|Golden Arch LLC.</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/polls/css/bootstrap.min.css" rel="stylesheet" />

  	<!-- fancyBox -->
	<link rel="stylesheet" href="/static/polls/css/fancybox/jquery.fancybox.css" type="text/css" media="screen" />

    <link href="{% static 'polls/css/main.css' %}" rel="stylesheet" />
    <!--<link href="/static/polls/css/main.css" rel="stylesheet" /> -->

     <script src="/static/polls/js/jquery/jquery-1.12.0.min.js"></script>

</head>
<body>
<div class="container">
    <div class="visible-sm-block visible-md-block visible-lg-block">
        <img u="image" src="{% static "polls/i/header.jpg" %}" class="img-responsive"/>
    </div>
                         
    <div class="visible-xs-block">
        <div><img u="image" src="/static/polls/i/header.jpg" class="img-responsive"/></div>
    </div>
</div>

<div class="container" >
    <div class="main-content">
            <form action="{% url 'polls:detail' question.id %}" method="post">
                {% csrf_token %}
                <div class="row featurette">
                    <div class="col-xs-12 col-sm-12 col-md-1"></div>
                    <div class="col-xs-12 col-sm-12 col-md-10">
                        <div style="float:inherit">
                            <h1>{{ question.question_text }}</h1><br/><br/>
                        </div>
                    </div>
                </div>
                <div class="row featurette">
                    <ul>
                    {% for choice in question.choice_set.all %}
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <li style="color: #1b3fa9; font-size:18px; font-weight:400; line-height:35px;	">
                            {{ choice.choice_text }} -- <span style="color:rgb(173, 4, 41)">{{ choice.votes }} vote{{ choice.votes|pluralize }}</span>
                        </li>
                    </div>
                    {% endfor %}
                    </ul>
                </div>
                <br/><br/><br/><br/>
                <div class="row featurette">
                    <div class="col-xs-12 col-sm-12 col-md-12" style="padding-left: 60px; vertical-align: top;">
                        <a href="{% url 'polls:detail' question.id %}"><img src="{% static "polls/i/btn_back.png" %}"/></a>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <a href="{% url 'polls:final' %}"><img src="{% static "polls/i/btn_viewall.png" %}"/></a>

                        <a href="{% url 'polls:raffle' %}"><img src="{% static "polls/i/btn_viewall.png" %}"/></a>
                    </div>
                </div>
            </form><br/><br/><br/><br/><br/><br/><br/><br/>
        <hr />  <!-- featurette-divider -->
        <!-- FOOTER -->
        <footer>
            <div class="copyRight">&copy; Copyright 2019 CN CONNECTION GOLDEN ARCH LLC. All Rights Reserved.</div>
        </footer>
        <br /><br />
    </div>

</div>
<!-- end of .container -->

<!-- Placed at the end of the document so the pages load faster -->
<script src="{% static "polls/js/plugin/bootstrap-3.3.6.min.js" %}"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script type="text/javascript" src="{% static "polls/js/plugin/ie10-viewport-bug-workaround.js" %}"></script>

<!-- fancybox -->
<script type="text/javascript" src="{% static "polls/js/plugin/jquery.fancybox.pack.js" %}"></script>

</body>
</html>

polls/templates/polls/thankyou.html
 <div class="col-xs-12 col-sm-12 col-md-8">

            <h2>Thank you for participating in our survey</h2><br/>



 </div>